language: cpp
dist: bionic
sudo: true
compiler: gcc

addons:
  apt:
    packages:
      - cmake
      - cppcheck
      - valgrind

before_script:
  - mkdir build && cd build
  - cmake ..
  - make
  - cp ../tests/test_data* .

jobs:
  include:
    - stage: static_analisys
      name: "Static analisys"
      script:
        - cppcheck --inconclusive --enable=all --language=c ../include/* ../src/*.c ../tests/*.c

    - stage: stress_test
      name: "Run stress_test"
      script:
        - ./stress_test

    - stage: memcheck
      name: "Memory checking"
      script:
        - valgrind --leak-check=full --leak-resolution=med --track-origins=yes --vgdb=no ./stress_test
