language: cpp
dist: bionic
sudo: true
compiler: gcc

addons:
  apt:
    packages:
      - cmake

before_script:
  - mkdir build && cd build
  - cmake ..
  - make
  - cp ../tests/test_data* .

jobs:
  include:
    - stage: stress_test
      name: "Run stress_test"
      script:
        - ./stress_test
